spring:
  application:
    name: serverwatch
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  jackson:
    serialization:
      write-dates-as-timestamps: false
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 3600
  
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
   
keycloak:
  auth-server-url: https://keycloak.derpb.com.br/realms/DERPB/broker/keycloak-oidc/endpoint
  realm: DERPB
  resource: serverwatch-client
  credentials:
    secret: your-client
    cliente-id: serverwatch-client
  use-resource-role-mappings: true
  bearer-only: true
  security-constraints:
    - authRoles:
        - user
      securityCollections:
        - patterns:
            - /api/*
server:
  port: 8080