/*
-- V1_0_0__create_tables.sql postgresql
*/
CREATE TABLE operation_systems (
    id bigint PRIMARY KEY,
    name character varying(100) NOT NULL
);

CREATE TABLE servers (
    id bigint PRIMARY KEY,
    name character varying(100) NOT NULL,
    ip_address character varying(45) NOT NULL UNIQUE,
    operation_system_id bigint,
    FOREIGN KEY (operation_system_id) REFERENCES operation_systems(id)
);

ALTER TABLE servers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

INSERT INTO operation_systems (id, name) VALUES
(1, 'Linux UBUNTU 20.04 LTS'),
(2, 'Windows Server 2016'),
(3, 'Windows Server 2019'),
(4, 'Windows Server 2022'),
(5, 'macOS Server 2022');
